// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsfdywvgubqwggshylnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzZmR5d3ZndWJxd2dnc2h5bG53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDIzODIsImV4cCI6MjA2MTAxODM4Mn0.vJ8h3IioxYCHmoTPX5flecjyL68FEUveZ2-faA-9Wkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);